import type { JobArea, JobWithCompany, CandidateWithProfile, ApplicationWithDetails } from "./types/database";

export const mockJobAreas: JobArea[] = [
  { id: 1,  name: "Ventas",             icon: "TrendingUp",    slug: "ventas" },
  { id: 2,  name: "Logística",          icon: "Truck",         slug: "logistica" },
  { id: 3,  name: "Manufactura",        icon: "Factory",       slug: "manufactura" },
  { id: 4,  name: "Administrativo",     icon: "Briefcase",     slug: "administrativo" },
  { id: 5,  name: "Tecnología",         icon: "Monitor",       slug: "tecnologia" },
  { id: 6,  name: "Servicio al cliente",icon: "Headphones",    slug: "servicio-cliente" },
  { id: 7,  name: "Finanzas",           icon: "DollarSign",    slug: "finanzas" },
  { id: 8,  name: "Recursos humanos",   icon: "Users",         slug: "recursos-humanos" },
  { id: 9,  name: "Operaciones",        icon: "Settings",      slug: "operaciones" },
  { id: 10, name: "Marketing",          icon: "Megaphone",     slug: "marketing" },
];

export const mockJobs: JobWithCompany[] = [
  {
    id: "1",
    title: "Asesor Comercial Externo",
    slug: "asesor-comercial-externo",
    description: `**Descripción del cargo**\n\nBuscamos un Asesor Comercial Externo con experiencia en ventas de campo, capaz de gestionar su propio portafolio de clientes y cumplir metas mensuales de ventas.\n\n**Responsabilidades principales**\n\n- Prospección y captación de nuevos clientes en zona asignada\n- Seguimiento a clientes activos para fidelización\n- Cumplimiento de presupuesto mensual de ventas\n- Reporte diario de actividades en CRM`,
    requirements: "- Mínimo 2 años de experiencia en ventas externas\n- Bachiller o técnico en áreas comerciales\n- Vehículo propio (indispensable)\n- Habilidades de negociación y cierre de ventas",
    benefits: "- Salario base + comisiones sin techo\n- Auxilio de rodamiento\n- Seguro de vida\n- Capacitaciones constantes",
    area_id: 1,
    area: mockJobAreas[0],
    modality: "presencial",
    contract_type: "tiempo_completo",
    salary_min: 1500000,
    salary_max: 4000000,
    salary_visible: true,
    city: "Medellín",
    department: "Antioquia",
    vacancies: 3,
    status: "active",
    featured: true,
    company_id: null,
    company: null,
    review_notes: null,
    created_by: "admin-1",
    expires_at: "2026-06-30T00:00:00Z",
    published_at: "2026-05-01T00:00:00Z",
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Auxiliar de Bodega",
    slug: "auxiliar-de-bodega",
    description: `**Descripción del cargo**\n\nRequerimos Auxiliar de Bodega para empresa del sector retail, encargado de recepción, almacenamiento y despacho de mercancía.\n\n**Responsabilidades principales**\n\n- Recepción y verificación de mercancía\n- Organización y control de inventarios\n- Alistamiento de pedidos\n- Manejo de montacargas (deseable)`,
    requirements: "- Bachiller académico\n- Experiencia mínima de 1 año en cargos similares\n- Manejo de sistemas de inventario\n- Disponibilidad para turnos rotativos",
    benefits: "- Salario básico + auxilio de transporte legal\n- Horas extra remuneradas\n- Afiliación a seguridad social\n- Estabilidad laboral",
    area_id: 2,
    area: mockJobAreas[1],
    modality: "presencial",
    contract_type: "temporal",
    salary_min: 1300000,
    salary_max: 1600000,
    salary_visible: true,
    city: "Bogotá",
    department: "Cundinamarca",
    vacancies: 5,
    status: "active",
    featured: false,
    company_id: null,
    company: null,
    review_notes: null,
    created_by: "admin-1",
    expires_at: "2026-06-15T00:00:00Z",
    published_at: "2026-05-05T00:00:00Z",
    created_at: "2026-05-05T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
  },
  {
    id: "3",
    title: "Desarrollador Frontend React",
    slug: "desarrollador-frontend-react",
    description: `**Descripción del cargo**\n\nBuscamos Desarrollador Frontend con experiencia en React y TypeScript para unirse a nuestro equipo de tecnología en modalidad híbrida.\n\n**Responsabilidades principales**\n\n- Desarrollo de interfaces de usuario con React y Next.js\n- Integración con APIs REST y GraphQL\n- Colaboración con el equipo de diseño UX/UI\n- Code reviews y documentación técnica`,
    requirements: "- Profesional o estudiante avanzado en Ingeniería de Sistemas o afines\n- Mínimo 2 años con React.js\n- Conocimiento de TypeScript, Tailwind CSS\n- Inglés técnico (deseable)",
    benefits: "- Trabajo híbrido (3 días en casa)\n- Bono de conectividad\n- Plan carrera\n- Capacitaciones en tecnología",
    area_id: 5,
    area: mockJobAreas[4],
    modality: "hibrido",
    contract_type: "tiempo_completo",
    salary_min: 3500000,
    salary_max: 6000000,
    salary_visible: true,
    city: "Medellín",
    department: "Antioquia",
    vacancies: 2,
    status: "active",
    featured: true,
    company_id: null,
    company: null,
    review_notes: null,
    created_by: "admin-1",
    expires_at: "2026-07-01T00:00:00Z",
    published_at: "2026-05-10T00:00:00Z",
    created_at: "2026-05-10T00:00:00Z",
    updated_at: "2026-05-10T00:00:00Z",
  },
  {
    id: "4",
    title: "Recepcionista / Auxiliar Administrativo",
    slug: "recepcionista-auxiliar-administrativo",
    description: `**Descripción del cargo**\n\nEmpresa del sector servicios requiere Recepcionista con buena presentación personal, habilidades comunicativas y manejo de herramientas ofimáticas.\n\n**Responsabilidades principales**\n\n- Atención al cliente presencial y telefónica\n- Manejo de agenda y correspondencia\n- Apoyo a procesos administrativos generales\n- Control de visitantes`,
    requirements: "- Técnico o tecnólogo en administración o afines\n- Experiencia mínima de 1 año\n- Manejo de Word, Excel\n- Excelente presentación personal",
    benefits: "- Contrato directo con la empresa\n- Horario de oficina (lunes a viernes)\n- Beneficios de ley",
    area_id: 4,
    area: mockJobAreas[3],
    modality: "presencial",
    contract_type: "tiempo_completo",
    salary_min: 1300000,
    salary_max: 1800000,
    salary_visible: true,
    city: "Cali",
    department: "Valle del Cauca",
    vacancies: 1,
    status: "active",
    featured: false,
    company_id: null,
    company: null,
    review_notes: null,
    created_by: "admin-1",
    expires_at: "2026-06-01T00:00:00Z",
    published_at: "2026-05-08T00:00:00Z",
    created_at: "2026-05-08T00:00:00Z",
    updated_at: "2026-05-08T00:00:00Z",
  },
  {
    id: "5",
    title: "Coordinador de Servicio al Cliente",
    slug: "coordinador-servicio-al-cliente",
    description: `**Descripción del cargo**\n\nBuscamos Coordinador de Servicio al Cliente para liderar un equipo de 8 asesores en call center de empresa de telecomunicaciones.\n\n**Responsabilidades principales**\n\n- Supervisión y coaching de equipo de asesores\n- Análisis de indicadores de calidad (NPS, FCR, AHT)\n- Gestión de escalados y clientes VIP\n- Reportes de gestión a gerencia`,
    requirements: "- Profesional en administración, ingeniería industrial o afines\n- Mínimo 2 años en roles de liderazgo en contact center\n- Manejo avanzado de Excel\n- Capacidad analítica y liderazgo",
    benefits: "- Salario competitivo + bono por cumplimiento\n- Trabajo híbrido\n- Seguro médico complementario\n- Días adicionales de vacaciones",
    area_id: 6,
    area: mockJobAreas[5],
    modality: "hibrido",
    contract_type: "tiempo_completo",
    salary_min: 2500000,
    salary_max: 3500000,
    salary_visible: true,
    city: "Bogotá",
    department: "Cundinamarca",
    vacancies: 1,
    status: "active",
    featured: false,
    company_id: null,
    company: null,
    review_notes: null,
    created_by: "admin-1",
    expires_at: "2026-06-20T00:00:00Z",
    published_at: "2026-05-12T00:00:00Z",
    created_at: "2026-05-12T00:00:00Z",
    updated_at: "2026-05-12T00:00:00Z",
  },
  {
    id: "6",
    title: "Analista de Recursos Humanos",
    slug: "analista-recursos-humanos",
    description: `**Descripción del cargo**\n\nRequerimos Analista de Recursos Humanos para apoyar los procesos de selección, contratación y bienestar laboral de nuestra organización.\n\n**Responsabilidades principales**\n\n- Publicación de vacantes y reclutamiento\n- Entrevistas y aplicación de pruebas psicotécnicas\n- Elaboración de contratos y afiliaciones\n- Apoyo en actividades de bienestar y clima organizacional`,
    requirements: "- Profesional en Psicología, Administración o afines\n- Experiencia mínima 1 año en selección de personal\n- Conocimiento en legislación laboral colombiana\n- Habilidades de comunicación e interpersonales",
    benefits: "- Contrato indefinido desde el inicio\n- Plan de carrera\n- Beneficios adicionales de ley\n- Ambiente de trabajo dinámico",
    area_id: 8,
    area: mockJobAreas[7],
    modality: "presencial",
    contract_type: "tiempo_completo",
    salary_min: 2000000,
    salary_max: 2800000,
    salary_visible: true,
    city: "Medellín",
    department: "Antioquia",
    vacancies: 1,
    status: "active",
    featured: false,
    company_id: null,
    company: null,
    review_notes: null,
    created_by: "admin-1",
    expires_at: "2026-06-25T00:00:00Z",
    published_at: "2026-05-14T00:00:00Z",
    created_at: "2026-05-14T00:00:00Z",
    updated_at: "2026-05-14T00:00:00Z",
  },
];

export const mockCandidates: CandidateWithProfile[] = [
  {
    id: "c1",
    birth_date: "1995-03-15",
    gender: "masculino",
    education_level: "profesional",
    career: "Ingeniería de Sistemas",
    years_experience: 3,
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL"],
    languages: ["Español", "Inglés"],
    linkedin_url: "https://linkedin.com/in/ejemplo",
    cv_url: null,
    cv_updated_at: null,
    availability: "15_dias",
    expected_salary: 4500000,
    summary: "Desarrollador frontend con 3 años de experiencia construyendo interfaces web con React y TypeScript.",
    profile_complete: true,
    profile: {
      id: "c1",
      full_name: "Carlos Martínez",
      email: "carlos@ejemplo.com",
      phone: "3001234567",
      city: "Medellín",
      role: "candidate",
      avatar_url: null,
      created_at: "2026-04-01T00:00:00Z",
      updated_at: "2026-04-01T00:00:00Z",
    },
  },
  {
    id: "c2",
    birth_date: "1998-07-22",
    gender: "femenino",
    education_level: "tecnologo",
    career: "Administración de Empresas",
    years_experience: 2,
    skills: ["Atención al cliente", "Excel", "Word", "CRM"],
    languages: ["Español"],
    linkedin_url: null,
    cv_url: null,
    cv_updated_at: null,
    availability: "inmediata",
    expected_salary: 1600000,
    summary: "Tecnóloga en administración con experiencia en servicio al cliente y manejo de herramientas ofimáticas.",
    profile_complete: true,
    profile: {
      id: "c2",
      full_name: "Laura Gómez",
      email: "laura@ejemplo.com",
      phone: "3157654321",
      city: "Bogotá",
      role: "candidate",
      avatar_url: null,
      created_at: "2026-04-05T00:00:00Z",
      updated_at: "2026-04-05T00:00:00Z",
    },
  },
];

export const mockApplications: ApplicationWithDetails[] = [
  {
    id: "app1",
    job_id: "3",
    candidate_id: "c1",
    status: "reviewing",
    cover_letter: "Me interesa mucho esta oportunidad ya que coincide con mi perfil técnico...",
    admin_notes: null,
    applied_at: "2026-05-15T10:00:00Z",
    updated_at: "2026-05-16T08:00:00Z",
    job: mockJobs[2],
    candidate: mockCandidates[0],
  },
  {
    id: "app2",
    job_id: "4",
    candidate_id: "c2",
    status: "pending",
    cover_letter: null,
    admin_notes: null,
    applied_at: "2026-05-18T14:00:00Z",
    updated_at: "2026-05-18T14:00:00Z",
    job: mockJobs[3],
    candidate: mockCandidates[1],
  },
];
